# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ActionSetup.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_actionDialog(object):
    def setupUi(self, actionDialog):
        actionDialog.setObjectName(_fromUtf8("actionDialog"))
        actionDialog.resize(590, 517)
        self.verticalLayout = QtGui.QVBoxLayout(actionDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.actShortInputLayout = QtGui.QGridLayout()
        self.actShortInputLayout.setSpacing(1)
        self.actShortInputLayout.setObjectName(_fromUtf8("actShortInputLayout"))
        self.actPathLabel = QtGui.QLabel(actionDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actPathLabel.sizePolicy().hasHeightForWidth())
        self.actPathLabel.setSizePolicy(sizePolicy)
        self.actPathLabel.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.actPathLabel.setFont(font)
        self.actPathLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.actPathLabel.setObjectName(_fromUtf8("actPathLabel"))
        self.actShortInputLayout.addWidget(self.actPathLabel, 2, 1, 1, 1)
        self.actTagLabel = QtGui.QLabel(actionDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actTagLabel.sizePolicy().hasHeightForWidth())
        self.actTagLabel.setSizePolicy(sizePolicy)
        self.actTagLabel.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.actTagLabel.setFont(font)
        self.actTagLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.actTagLabel.setObjectName(_fromUtf8("actTagLabel"))
        self.actShortInputLayout.addWidget(self.actTagLabel, 0, 1, 1, 1)
        self.actNameLabel = QtGui.QLabel(actionDialog)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.actNameLabel.setFont(font)
        self.actNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.actNameLabel.setObjectName(_fromUtf8("actNameLabel"))
        self.actShortInputLayout.addWidget(self.actNameLabel, 1, 1, 1, 1)
        self.actTagLineEdit = QtGui.QLineEdit(actionDialog)
        self.actTagLineEdit.setObjectName(_fromUtf8("actTagLineEdit"))
        self.actShortInputLayout.addWidget(self.actTagLineEdit, 0, 2, 1, 1)
        self.actNameLineEdit = QtGui.QLineEdit(actionDialog)
        self.actNameLineEdit.setObjectName(_fromUtf8("actNameLineEdit"))
        self.actShortInputLayout.addWidget(self.actNameLineEdit, 1, 2, 1, 1)
        self.actPathLineEdit = QtGui.QLineEdit(actionDialog)
        self.actPathLineEdit.setObjectName(_fromUtf8("actPathLineEdit"))
        self.actShortInputLayout.addWidget(self.actPathLineEdit, 2, 2, 1, 1)
        self.actPassiveRadio = QtGui.QRadioButton(actionDialog)
        self.actPassiveRadio.setChecked(True)
        self.actPassiveRadio.setObjectName(_fromUtf8("actPassiveRadio"))
        self.actShortInputLayout.addWidget(self.actPassiveRadio, 1, 3, 1, 1)
        self.actActiveRadio = QtGui.QRadioButton(actionDialog)
        self.actActiveRadio.setObjectName(_fromUtf8("actActiveRadio"))
        self.actShortInputLayout.addWidget(self.actActiveRadio, 0, 3, 1, 1)
        self.passiveBeforeCheck = QtGui.QCheckBox(actionDialog)
        self.passiveBeforeCheck.setObjectName(_fromUtf8("passiveBeforeCheck"))
        self.actShortInputLayout.addWidget(self.passiveBeforeCheck, 2, 3, 1, 1)
        self.verticalLayout.addLayout(self.actShortInputLayout)
        self.actBotLayout = QtGui.QHBoxLayout()
        self.actBotLayout.setSpacing(1)
        self.actBotLayout.setObjectName(_fromUtf8("actBotLayout"))
        self.actTriggerLayout = QtGui.QVBoxLayout()
        self.actTriggerLayout.setSpacing(0)
        self.actTriggerLayout.setObjectName(_fromUtf8("actTriggerLayout"))
        self.actTriggerTopLayout = QtGui.QHBoxLayout()
        self.actTriggerTopLayout.setObjectName(_fromUtf8("actTriggerTopLayout"))
        self.actTriggerLabel = QtGui.QLabel(actionDialog)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.actTriggerLabel.setFont(font)
        self.actTriggerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.actTriggerLabel.setObjectName(_fromUtf8("actTriggerLabel"))
        self.actTriggerTopLayout.addWidget(self.actTriggerLabel)
        self.actTriggerLineEdit = QtGui.QLineEdit(actionDialog)
        self.actTriggerLineEdit.setObjectName(_fromUtf8("actTriggerLineEdit"))
        self.actTriggerTopLayout.addWidget(self.actTriggerLineEdit)
        self.actTriggerLayout.addLayout(self.actTriggerTopLayout)
        self.actTriggerList = QtGui.QListWidget(actionDialog)
        self.actTriggerList.setObjectName(_fromUtf8("actTriggerList"))
        self.actTriggerLayout.addWidget(self.actTriggerList)
        self.actBotLayout.addLayout(self.actTriggerLayout)
        self.actReturnLayout = QtGui.QGridLayout()
        self.actReturnLayout.setObjectName(_fromUtf8("actReturnLayout"))
        self.actSelectReturnList = QtGui.QListWidget(actionDialog)
        self.actSelectReturnList.setObjectName(_fromUtf8("actSelectReturnList"))
        self.actReturnLayout.addWidget(self.actSelectReturnList, 1, 1, 1, 1)
        self.actAvailReturnList = QtGui.QListWidget(actionDialog)
        self.actAvailReturnList.setObjectName(_fromUtf8("actAvailReturnList"))
        self.actReturnLayout.addWidget(self.actAvailReturnList, 1, 0, 1, 1)
        self.actAvailReturnLabel = QtGui.QLabel(actionDialog)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.actAvailReturnLabel.setFont(font)
        self.actAvailReturnLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.actAvailReturnLabel.setObjectName(_fromUtf8("actAvailReturnLabel"))
        self.actReturnLayout.addWidget(self.actAvailReturnLabel, 0, 0, 1, 1)
        self.actSelectReturnLabel = QtGui.QLabel(actionDialog)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.actSelectReturnLabel.setFont(font)
        self.actSelectReturnLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.actSelectReturnLabel.setObjectName(_fromUtf8("actSelectReturnLabel"))
        self.actReturnLayout.addWidget(self.actSelectReturnLabel, 0, 1, 1, 1)
        self.actBotLayout.addLayout(self.actReturnLayout)
        self.verticalLayout.addLayout(self.actBotLayout)

        self.retranslateUi(actionDialog)
        QtCore.QMetaObject.connectSlotsByName(actionDialog)

    def retranslateUi(self, actionDialog):
        actionDialog.setWindowTitle(_translate("actionDialog", "Setup Action", None))
        self.actPathLabel.setText(_translate("actionDialog", "Path", None))
        self.actTagLabel.setText(_translate("actionDialog", "Tag ", None))
        self.actNameLabel.setText(_translate("actionDialog", "Name", None))
        self.actPassiveRadio.setText(_translate("actionDialog", "Passive", None))
        self.actActiveRadio.setText(_translate("actionDialog", "Active", None))
        self.passiveBeforeCheck.setText(_translate("actionDialog", "Before Trigger", None))
        self.actTriggerLabel.setText(_translate("actionDialog", "Trigger", None))
        self.actAvailReturnLabel.setText(_translate("actionDialog", "Available Returns", None))
        self.actSelectReturnLabel.setText(_translate("actionDialog", "Selected Returns", None))

