package:
  name: lazylyst
  version: "0.7.4"

source:
  fn: lazylyst-0.7.4.tar.gz
  md5: 60ead8e6a4748b6b664c292dc01f106c
  url: https://pypi.python.org/packages/53/ef/4848fed2db6142951389ee20ffabb0891e3274d14bdc1ad40683ff307d8f/lazylyst-0.7.4.tar.gz

requirements:
  build:
    - python
    - setuptools
    - sip
    - future
    - obspy >=1.1.0
    - scandir
    - pyqtgraph ==0.10.0
    - pyproj >=1.9.5.1
    - pyqt

  run:
    - python
    - sip
    - future
    - obspy >=1.1.0
    - scandir
    - pyqtgraph ==0.10.0
    - pyproj >=1.9.5.1
    - pyqt

test:
  imports:
    - lazylyst

about:
  home: https://github.com/AndrewReynen/Lazylyst
  license: MIT License
  license_file: LICENSE
  summary: GUI created for time series review, using a flexible framework for new workflows